config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root to: 'items#index'
resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  validates :recipes             ,presence: true, length: { maximum: 255 }
  validates :description         ,presence: true
  validates :image, presence: true

  belongs_to :user
  has_one :reserve
  has_one_attached :image




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  validates :first_name, presence: true, format:{ with: /\A[a-zA-Z]+\z/, message: 'は半角英字のみで入力してください' }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: 'は半角英字のみで入力してください' }


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :nickname, :first_name, :last_name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def index
   @items = Item.all

   
end

def new
  @item = Item.new
end



def create
  @item = Item.new(item_params)

  if @item.save

    redirect_to root_path

  else
    render :new

  end
  
end

def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

private

def item_params
  params.require(:item).permit(:description, :recipes, :image).merge(user_id: current_user.id)
end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
  
    <%# <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %> 
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with(model:@item,url: item_path,local: true) do |f| %>
    <%# <%= render 'shared/error_messages', model: f.object %> 

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          recipes
          <span class="indispensable">必須</span>
        </div>
        <%# <%= f.collection_select(:recipes, Recipes.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %> %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%# <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %> %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%# <%= f.collection_select(:fee_id, Fee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %> %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%# <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %> %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%# <%= f.collection_select(:deliverytime_id, Deliverytime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %> %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" , class:"sell-btn" %>
      <%= link_to 'もどる', item_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%# <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %> 
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<%# <html lang="en"> %>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Product example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }


      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    
<header class="site-header sticky-top py-1">
  <nav class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="#" aria-label="Product">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
    </a>
    <a class="py-2 d-none d-md-inline-block" href="#">Tour</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Product</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Features</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>
  </nav>
</header>

<main>
  

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 fw-normal">Let's experience "Itadakimasu"</h1>
    <div class="my-3">
      <p class="lead fw-normal">Home visit connected with the world.</p>
      <button id="reserve-btn-text">Reserve</button>
    </div>
  </div>
</div>




    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <%# <div class="bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div> %>

  <div class='title-contents'>
    <%= image_tag "img-top.gif", class:"list-pict" %>
    <%= image_tag "bbq.jpg", class:"list-pict" %>
      </div>












      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <%# <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div> %>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>





<ul class="item-list">
  <% if @items.present? %>  
    <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %> 
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.recipes %>
            </h3>
          </div>
        <% end %>  
      </li>
    <% end %>
</ul>










  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-primary me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>

  <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>
      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5">Another headline</h2>
        <p class="lead">And an even wittier subheading.</p>
      </div>









      <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>
</main>

<%= render "shared/footer" %>


<%# <footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017–2021</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
        <li><a class="link-secondary" href="#">Another one</a></li>
        <li><a class="link-secondary" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Resource name</a></li>
        <li><a class="link-secondary" href="#">Resource</a></li>
        <li><a class="link-secondary" href="#">Another resource</a></li>
        <li><a class="link-secondary" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Business</a></li>
        <li><a class="link-secondary" href="#">Education</a></li>
        <li><a class="link-secondary" href="#">Government</a></li>
        <li><a class="link-secondary" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>
 %>









          <%# </h3>
          <div class='item-price'>
            <span><%= item.price円<br><%= item.fee.name</span> 
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <%# <span class='star-count'>0</span> %>
            <%# </div> 
          </div>  
        </div>
        <% end %>  
      </li>
       <% end %>
        <%# <% else %>   
      <%# <li class='list'>
        <%= link_to '#' do %> 
        <%# <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <%# <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！ 
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>  %>
              <%# <%= image_tag "star.png", class:"star-icon" %> 
              <%# <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      <%# </li>
      <% end %>
    <%# </ul>
  </div> 
  <%# /商品一覧 %>
<%# </div>    %>





    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>Submit</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

      
  </body>

app/views/items/show.html.erb
<%= render "shared/header" %>
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.recipes %>
    </h2>
    
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
      <%# <% if Order.exists?(item_id: @item.id) %>
      
      
      <%# <div class="sold-out"> 
        <span>Sold Out!!</span> 
       </div>   %>

       <%# <% end %> 
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥<%=5000%>
      </span>
      <%# <span class="item-postage">
        <%= @item.fee.name %>
      <%# </span>  %>
    </div>


    <%# <% if user_signed_in? && current_user == @item.user&& !Order.exists?(item_id: @item.id) %> 
    <%= link_to "edit the menu", edit_item_path, method: :get, class: "item-red-btn" %>
    <p class="or-text">or</p>
    
    <%= link_to "delete", item_path, method: :delete, class:"item-destroy" %>
    <%# <% elsif user_signed_in? && !Order.exists?(item_id: @item.id) %> 
    <%= link_to "reserve", item_path ,class:"item-red-btn"%>
    <%# <% end %>


    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">family name</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <%# <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        <%# </tr>  %>
        <%# <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <%# <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.fee.name %></td>
        </tr>
        <tr>
          <%# <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.area.name %></td> 
        </tr>
        <tr>
          <%# <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.deliverytime.name %></td> 
        </tr>  
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%# <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%> 
        <span>your favorite</span>
      </div>
      <div class="report-btn">
        <%# <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%> 
        <span>Report the products</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <%# <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p> %>
      <%# <button type="submit" class="comment-btn">
        <%# <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%> 
        <%# <span>コメントする<span>
      </button>
    </form>
  </div> %> 
  <%# <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div> %>
  <%# <a href="#" class="another-item"><%= @item.category.name %></a> 
</div>

<%# <%= render "shared/footer" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Original39061</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    Everyone can use the Minshoku service
  </p>
  <h2 class='ad-footer-title'>
    Please down load this application
  </h2>
  <div class='store-btn'>
    <%# <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %> 
    <%# <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %> 
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>About minshoku</h2>
      <ul>
        <li><%= link_to 'Company Profile（Operating Company)', "#", class: "footer-link" %></li>
        <li><%= link_to 'Privacy Policy', "#", class: "footer-link" %></li>
        <li><%= link_to 'Terms of Use', "#", class: "footer-link" %></li>
        <li><%= link_to 'Special Terms and Conditions for Points', "#", class: "footer-link" %></li>
        <li><%= link_to 'Inquiry', "inquiry_items_path", class: "footer-link" %></li>


      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%# <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %> 
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<%# <header class='top-page-header'>
  <div class='search-bar-contents'> %>
    <%# <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %> 
    <%# <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button"> %>
        <%# <%= image_tag "search.png", class:"search-icon" %> 
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <%# <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <%# <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>  
    </ul>
    <ul class='lists-right'>
      
      
      
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, root_path(current_user.id), class: "user-nickname" %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %></li>
      
      
      <% else %>
      <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
      <li><%= link_to 'Registration', new_user_registration_path, class: "sign-up" %></li>
      </div>
      <% end %>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>